from __future__ import annotations

POLICY_ERROR_REGISTRY_VERSION = 1

POLICY_ERROR_CODES = (
    "POLICY_CONFLICT",
    "POLICY_DUPLICATE_DISCOVERY_ROUTE",
    "POLICY_DUPLICATE_PROFILE_ID",
    "POLICY_DUPLICATE_SET_MEMBER",
    "POLICY_DUPLICATE_YAML_KEY",
    "POLICY_FILE_MISSING",
    "POLICY_MALFORMED",
    "POLICY_PROFILE_DOWNGRADE_FORBIDDEN",
    "POLICY_PROFILE_REQUIRED_FILE_INVALID",
    "POLICY_TYPE_ERROR",
    "POLICY_UNKNOWN_ATTRIBUTE",
    "POLICY_UNKNOWN_ATTRIBUTE_VALUE",
    "POLICY_UNKNOWN_FIELD",
    "POLICY_UNKNOWN_ID",
    "POLICY_UNSUPPORTED_VERSION",
)
