from __future__ import annotations

WORKFLOW_ERROR_REGISTRY_VERSION = 1

WORKFLOW_ERROR_CODES = (
    "WORKFLOW_INVALID_INPUT",
    "WORKFLOW_UNKNOWN_STATE",
    "WORKFLOW_ILLEGAL_TRANSITION",
    "WORKFLOW_POLICY_RESULT_INVALID",
    "WORKFLOW_HUMAN_GATE_REQUIRED",
    "WORKFLOW_EVIDENCE_MISSING",
    "WORKFLOW_EVIDENCE_HASH_MISMATCH",
    "WORKFLOW_AUDIT_CORRUPT",
    "WORKFLOW_STATE_CORRUPT",
    "WORKFLOW_IDEMPOTENCY_CONFLICT",
    "WORKFLOW_CONCURRENT_WRITE",
    "WORKFLOW_UNSUPPORTED_SCHEMA_VERSION",
    "WORKFLOW_TASK_ALREADY_EXISTS",
    "WORKFLOW_DECISION_BINDING_INVALID",
    "WORKFLOW_TRANSACTION_INCOMPLETE",
    "WORKFLOW_COORDINATED_REWRITE_OUT_OF_SCOPE",
)
